PatTuring2016.MVCWeb/Controllers/DemoController.cs
//-----------------------------------------------------------------------
// <copyright file="DemoController.cs" company="Thinking Solutions Pty Ltd">
//     Copyright (c) Thinking Solutions 2015. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

using PatTuring2015.ServiceProxy.Facades;
using PatTuring2015.ServiceProxy.ViewModels;
using PatTuring2016.Common.ScreenModels.FullScreenModels;
using System.Web.Mvc;

namespace PatTuring2016.MVCWeb.Controllers
{
    [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
    public class DemoController : Controller
    {
        private readonly DemoServiceFacade _demoServiceFacade;
        private readonly SettingsServiceFacade _settingsServiceFacade;

        public DemoController(DemoServiceFacade demoServiceFacade, SettingsServiceFacade settingsServiceFacade)
        {
            _demoServiceFacade = demoServiceFacade;
            _settingsServiceFacade = settingsServiceFacade;
        }

        [HttpGet]
        public ActionResult Index(string text)
        {
            var getText = _demoServiceFacade.GetText(text);
            var settings = _settingsServiceFacade.GetSettings();
            var samplesettings = _settingsServiceFacade.GetSampleSettings();

            if (getText != null)
            {
                var demo = new DemoViewModel { Match = getText.Match, Settings = settings, SampleSettings = samplesettings };

                if (getText.EditFound)
                {
                    return View(demo);
                }
            }
            else
            {
                return View();
            }

            var demo1 = new DemoViewModel { Match = getText.Match, Settings = settings, SampleSettings = samplesettings };

            return getText.TextToUseFound ? Index(demo1) : View();
        }

        [HttpPost]
        public ActionResult Index(DemoViewModel viewModel)
        {
            _settingsServiceFacade.UpdateSettings(viewModel.Settings, viewModel.SampleSettings);

            var getmatch = _demoServiceFacade.GetMatchFor(viewModel.Match);

            if (getmatch.MatchesSuccessfullyFound)
            {
                return RedirectToAction(getmatch.MenuType);
            }

            // no match - display for edit
            ViewBag.ErrorMessage = getmatch.Message;

            return View(viewModel);
        }

        public ActionResult Back()
        {
            return RedirectToAction(_demoServiceFacade.Back());
        }

        public ActionResult Restart()
        {
            return RedirectToAction(_demoServiceFacade.Restart());
        }

        public ActionResult Select(int selection)
        {
            _demoServiceFacade.SelectFor(selection);
            return RedirectToAction("FullScreen");
        }

        public ActionResult SelectWord()
        {
            _demoServiceFacade.SelectWordFor();
            return RedirectToAction("FullScreen");
        }

        public ActionResult MoreDetail(int type)
        {
            _demoServiceFacade.MoreDetailFor(type);
            return RedirectToAction("FullScreen");
        }

        public ActionResult MoreChangeDetail(int type, int part)
        {
            _demoServiceFacade.MoreChangeDetailFor(type, part);
            return RedirectToAction("FullScreen");
        }
        public ActionResult MoreGridDetail(int type, int part)
        {
            _demoServiceFacade.MoreGridDetailFor(type, part);
            return RedirectToAction("FullScreen");
        }

        public ActionResult MoreGridSense(int type, int part)
        {
            _demoServiceFacade.MoreGridSenseFor(type, part);
            return RedirectToAction("FullScreen");
        }

        public ActionResult MoreSense(int type, int part)
        {
            _demoServiceFacade.MoreSenseFor(type, part);
            return RedirectToAction("FullScreen");
        }

        public ActionResult Sentences()
        {
            var screen = _demoServiceFacade.GetCurrentScreen();
            return View(screen.ScreenModel as StandardScreenModel);
        }

        public ActionResult ClauseStart()
        {
            var screen = _demoServiceFacade.GetCurrentScreen();
            return !screen.SimpleView ? View(screen.ScreenModel as FullClauseScreenModel) : View("SimpleClauseStart", screen.ScreenModel as FullClauseScreenModel);
        }

        public ActionResult FullScreen()
        {
            var screen = _demoServiceFacade.GetCurrentScreen();
            switch (screen.ScreenName)
            {
                case "Word": return PartialView("Word", screen.ScreenModel as WordScreenModel);
                case "Fullword": return PartialView("FullWord", screen.ScreenModel as WordScreenModel);
                case "Sense": return PartialView("Sense", screen.ScreenModel as SenseScreenModel);
                case "Senses": return PartialView("Senses", screen.ScreenModel as SensesScreenModel);
                case "Sentence": return PartialView("Sentence", screen.ScreenModel as SentenceScreenModel);
                case "Phrase": return PartialView("Phrase", screen.ScreenModel as PhraseScreenModel);
                case "Clause":
                    {
                        var model = (FullClauseScreenModel)screen.ScreenModel;
                        return !screen.SimpleView ? PartialView("Partials/Clause", model) : PartialView("SimplePartials/SimpleClause", model);
                    }
                case "Noun":
                    {
                        var model = (FullNounScreenModel)screen.ScreenModel;
                        return !screen.SimpleView ? PartialView("NounClause", model) : PartialView("SimplePartials/SimpleNounClause", model);
                    }

                default: return PartialView(screen.ScreenName, screen.ScreenModel);
            }
        }
    }
}

PatTuring2016.MVCWeb/Views/Shared/AjaxButtons.cshtml
<div id="consolenav">
    <span class="button">@Ajax.ActionLink("back", "Back", "Demo",
                             new AjaxOptions
                             {
                                 UpdateTargetId = "console",
                                 InsertionMode = InsertionMode.Replace,
                                 HttpMethod = "GET"
                             })
    </span>&nbsp;<span class="button">@Ajax.ActionLink("last match", "Restart", "Demo",
                                          new AjaxOptions
                                          {
                                              UpdateTargetId = "console",
                                              InsertionMode = InsertionMode.Replace,
                                              HttpMethod = "GET"
                                          })
    </span>&nbsp;<span class="button">@Html.ActionLink("new match", "Index", "Demo")</span>
</div>

PatTuring2016.MVCWeb/Views/Shared/_AppLayout.cshtml
@using PatTuring2016.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Thinking Solutions</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <a class="left" href="http://www.thinkingsolutions.com.au"><img src="@Url.Content("~/Content/Images/TSLogoSmall.jpg")" alt="Home"/></a>
            <p class="site-title indent">
                @Html.ActionLink(
                    "Change Application", "Index", "Splash")
            </p>
        </div>
    </header>
    <div id="body">
        <section class="content-wrapper clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="indent">
                    &copy; @DateTime.Now.Year - Thinking Solutions Pty Ltd. All Rights Reserved. Online
                    Version @Const.GetEnumName(PatomValues.Version)
                </p>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

PatTuring2016.MVCWeb/Views/Shared/_ChoiceLayout.cshtml
@using PatTuring2016.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Thinking Solutions</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="content-wrapper redbg">
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
            </div>
            <h3 class="indent">Please select an option below to continue:</h3>
        </div>
    </header>
    <div id="body" class="redbg">
        <section class="content-wrapper clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="indent">
                    &copy; @DateTime.Now.Year - Thinking Solutions Pty Ltd. All Rights Reserved. Online
                    Version @Const.GetEnumName(PatomValues.Version)
                </p>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

PatTuring2016.MVCWeb/Views/Shared/_ConsoleLayout.cshtml
@Html.Partial("AjaxButtons")
@RenderBody()

PatTuring2016.MVCWeb/Views/Shared/_Layout.cshtml
@using PatTuring2016.Common
@using PatTuring2016.MVCWeb.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-31567866-1']);
        _gaq.push(['_setDomainName', 'thinkingsolutions.com.au']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <a class="left" href="http://www.thinkingsolutions.com.au"><img src="@Url.Content("~/Content/Images/TSLogoSmall.jpg")" alt="Home" /></a>
                <p class="left site-title">
                    @Html.ActionLink(
                        "Change Application", "Index", "Splash")
                </p>
            </div>
        </div>
        <div class="float-right">
            <section id="login">
                @Html.Partial("_LoginPartial")
            </section>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Demo", "Index", "Demo")</li>
                    <li>@Html.ActionLink("Samples", "Index", "Samples")</li>
                    <li>@Html.ActionLink("Help", "Help", "Home")</li>
                    <li>@Html.ActionLink("Releases", "Releases", "Home")</li>
                </ul>
            </nav>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            <div id="console">
                @RenderBody()
            </div>
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>
                    Project Turing: Copyright &copy; Thinking Solutions Pty Ltd @DateTime.Now.Year. All Rights Reserved. Online
                    Version @Versioning.Current
                </p>
            </div>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

PatTuring2016.MVCWeb/Views/Shared/_SplashLayout.cshtml
@using PatTuring2016.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Thinking Solutions</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
            </div>
            <h3 class="indent">Please select an option below to continue:</h3>
        </div>
    </header>
    <div id="body">
        <section class="content-wrapper clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="indent">
                    &copy; @DateTime.Now.Year - Thinking Solutions Pty Ltd. All Rights Reserved. Online
                    Version @Const.GetEnumName(PatomValues.Version)
                </p>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>