PatTuring2016.MVCWeb/Controllers/ConverseController.cs
//-----------------------------------------------------------------------
// <copyright file="ConverseController.cs" company="Thinking Solutions Pty Ltd">
//     Copyright (c) Thinking Solutions 2015. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

using PatTuring2015.ServiceProxy.Facades;
using PatTuring2016.Common.ScreenModels;
using System.Web.Mvc;

namespace PatTuring2016.MVCWeb.Controllers
{
    public class ConverseController : Controller
    {
        private readonly ConverseServiceFacade _converseService;

        public ConverseController(ConverseServiceFacade converseService)
        {
            _converseService = converseService;
        }

        public ActionResult Index(ConverseViewModel model)
        {
            var match = new Match();

            if (model != null)
            {
                if (model.Match != null)
                {
                    if (!string.IsNullOrWhiteSpace(model.Match.TextIn))
                    {
                        match.TextIn = model.Match.TextIn;
                    }
                }
            }

            var getmatch = _converseService.UpdateConversation(match);
            var newmodel = new ConverseViewModel { Conversation = getmatch, Match = new Match() };

            return View(newmodel);
        }

        public ActionResult Context(ConverseViewModel model)
        {
            var match = new Match { TextIn = "Context" };

            if (model != null)
            {
                if (model.Match != null)
                {
                    if (!string.IsNullOrWhiteSpace(model.Match.TextIn))
                    {
                        match.TextIn = model.Match.TextIn;
                    }
                }
            }

            var getmatch = _converseService.GetContext(match);
            var newmodel = new ConverseViewModel { Conversation = getmatch, Match = new Match() };

            return View(newmodel);
        }

        public ActionResult Tracker(ConverseViewModel model)
        {
            var match = new Match { TextIn = "Context" };

            if (model != null)
            {
                if (model.Match != null)
                {
                    if (!string.IsNullOrWhiteSpace(model.Match.TextIn))
                    {
                        match.TextIn = model.Match.TextIn;
                    }
                }
            }

            var getmatch = _converseService.GetContext(match);
            var newmodel = new ConverseViewModel { Conversation = getmatch, Match = new Match() };

            return View(newmodel);
        }

        public ActionResult Restart(ConverseViewModel model)
        {
            var match = new Match();

            if (model != null)
            {
                if (model.Match != null)
                {
                    if (!string.IsNullOrWhiteSpace(model.Match.TextIn))
                    {
                        match.TextIn = model.Match.TextIn;
                    }
                }
            }

            _converseService.RestartConversation(match);

            return RedirectToAction("Index");
        }
    }
}

PatTuring2016.MVCWeb/Views/Converse/Context.cshtml
@if (IsAjax)
{
    Layout = null;
}
@model PatTuring2016.Common.ScreenModels.ConverseViewModel
@{
    Layout = "~/Views/Shared/_AppLayout.cshtml";
    ViewBag.Title = "Context";
}
<div id="converse">
    <h1>Context Screen</h1>
    <p class="white">
        This screen provides the tracking details of a conversation in progress. Context is a way to track
        who is talking to whom, where and when. At present, the computer keeps track of when by resetting its clock for each
        new conversation.
    </p>

    <h3>Specific Values (where am I, who are you,...)</h3>
    <table>
        <tr>
            <th class="narrow1">Element</th>
            <th>Current Value</th>
        </tr>
        @foreach (var item in @Model.Conversation.HighTrackingData.HighContextList)
        {
            <tr>
                <td class="narrow1">@item.Element</td>
                <td>@item.Value</td>
            </tr>
        }
    </table>

    <h3>Variable Values (including other pronouns, i.e. not me or you)</h3>
    <table>
        <tr>
            <th class="narrow1">Clause Piece</th>
            <th>Elements</th>
            <th class="narrow2">Logical Structure</th>
            <th>Clause Matched</th>
        </tr>
        @foreach (var item in @Model.Conversation.PronounTrackingData.PronounList)
        {
            <tr>
                <td class="narrow1">
                    <ul class="inTable">
                        @foreach (var part in @item.ClausePart)
                        {
                            <li>@part</li>
                        }
                    </ul>
                </td>
                <td>
                    <ul class="inTable">
                        @foreach (var part in @item.ClauseElements)
                        {
                            if (!string.IsNullOrWhiteSpace(part))
                            {
                                <li>@part</li>
                            }
                        }
                    </ul>
                </td>
                <td class="narrow1">@Html.Raw(item.LS)</td>
                <td>
                    <p class="bold">@item.Clause</p>
                    <ul class="inTable">
                        @foreach (var part in @item.Information)
                        {
                            if (!string.IsNullOrWhiteSpace(part))
                            {
                                <li>@part</li>
                            }
                        }
                    </ul>
                </td>
            </tr>
        }

    </table>

    <p></p>
    <span class="button1">
        @Html.ActionLink("Return to Current Conversation", "Index", "Converse")
    </span>

    @if (@ViewBag.ErrorMessage != "")
    {
        <h3 id="Error">@ViewBag.ErrorMessage</h3>
    }
</div>

PatTuring2016.MVCWeb/Views/Converse/Index.cshtml
@model PatTuring2016.Common.ScreenModels.ConverseViewModel
@{
    ViewBag.Title = "Conversation";
    Layout = "~/Views/Shared/_AppLayout.cshtml";
}
@if (IsAjax)
{
    Layout = null;
}
<div id="converse">
    @using (Html.BeginForm())
    {
        <h2>Enter your conversational text</h2>
        <span>
            <span>(full sentences, please)</span>
            @Html.EditorFor(model => model.Match.TextIn)
        </span>
        <span class="spacetop">
            <input type="submit" value="Say it!" />
        </span>
    }

    <div id="ts-head">
        @if (Model.Conversation.CurrentResponse != null)
        {

            <p class="redspeech">@Model.Conversation.CurrentResponse.WhatSaid</p>
        }
    </div>
    <div class="topmargin">
        <span class="button1">
            @Html.ActionLink("New conversation", "Restart", "Converse")
        </span>
        <span class="button1">
            @Html.ActionLink("View Current Context", "Context", "Converse")
        </span>
        <span class="button1">
            @Html.ActionLink("View Current Conversation List", "Tracker", "Converse")
        </span>
    </div>

    @if (@ViewBag.ErrorMessage != "")
    {
        <h3 id="Error">@ViewBag.ErrorMessage</h3>
    }
</div>

PatTuring2016.MVCWeb/Views/Converse/Tracker.cshtml
@model PatTuring2016.Common.ScreenModels.ConverseViewModel
@{
    ViewBag.Title = "Conversation";
    Layout = "~/Views/Shared/_AppLayout.cshtml";
}
@if (IsAjax)
{
    Layout = null;
}
<div id="converse">
    <h1>Conversation Tracking Screen</h1>
    <table>
        <tr>
            <th class="narrow1">Spoken by</th>
            <th>What was said</th>
            <th>When</th>
        </tr>

        @foreach (var item in @Model.Conversation.TrackingData.SpokenList)
        {
            <tr>
                <td class="narrow1">@item.Speaker</td>
                <td>@item.WhatSaid</td>
                <td>@item.WhenSaid</td>
            </tr>
        }
    </table>
    <p></p>
    <span class="button1">
        @Html.ActionLink("View Current Context", "Context", "Converse")
    </span>
    <span class="button1">
        @Html.ActionLink("Return", "Index", "Converse")
    </span>

    @if (@ViewBag.ErrorMessage != "")
    {
        <h3 id="Error">@ViewBag.ErrorMessage</h3>
    }
</div>